language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - echo '********** Build start'
  - echo '********** Installing dependencies'
  - npm install
  - echo '*********** Running tests and coverage'
  - npm run coverage

